//! Field type definitions and metadata

use std::fmt;

/// Supported field types in search indices
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldType {
    /// Full-text searchable text field
    Text,
    /// Exact-match keyword field
    Keyword,
    /// Numeric field (integers and floats)
    Numeric,
    /// Date/time field
    Date,
    /// Geospatial field (lat/lon)
    Geo,
    /// Nested object
    Nested,
    /// Boolean field
    Boolean,
}

impl fmt::Display for FieldType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            FieldType::Text => write!(f, "text"),
            FieldType::Keyword => write!(f, "keyword"),
            FieldType::Numeric => write!(f, "numeric"),
            FieldType::Date => write!(f, "date"),
            FieldType::Geo => write!(f, "geo_point"),
            FieldType::Nested => write!(f, "nested"),
            FieldType::Boolean => write!(f, "boolean"),
        }
    }
}

/// Options that can be applied to fields
#[derive(Debug, Clone, Default)]
pub struct FieldOptions {
    /// Whether the field value should be stored (returned in search results)
    pub stored: bool,

    /// Whether the field can be used for sorting
    pub sortable: bool,

    /// Enable prefix search (creates edge n-gram analyzer)
    pub prefix: bool,

    /// Enable case-insensitive matching
    pub case_insensitive: bool,

    /// Enable fuzzy matching
    pub fuzzy: bool,

    /// Custom analyzer name
    pub analyzer: Option<String>,

    /// Minimum n-gram size for prefix search (default: 1)
    pub min_gram: Option<u32>,

    /// Maximum n-gram size for prefix search (default: 20)
    pub max_gram: Option<u32>,
}

/// Metadata about a field, generated by the derive macro
#[derive(Debug, Clone)]
pub struct FieldMetadata {
    /// Field name
    pub name: &'static str,

    /// Field type
    pub field_type: FieldType,

    /// Field options
    pub options: FieldOptions,
}

impl FieldMetadata {
    pub const fn new(name: &'static str, field_type: FieldType) -> Self {
        Self {
            name,
            field_type,
            options: FieldOptions {
                stored: false,
                sortable: false,
                prefix: false,
                case_insensitive: false,
                fuzzy: false,
                analyzer: None,
                min_gram: None,
                max_gram: None,
            },
        }
    }

    pub const fn stored(mut self, value: bool) -> Self {
        self.options.stored = value;
        self
    }

    pub const fn sortable(mut self, value: bool) -> Self {
        self.options.sortable = value;
        self
    }
}
